variables:
  NODE_VERSION: 20

stages:
  - build
  - deploy

yarn build:
  image: node:$NODE_VERSION
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    name: "build-$CI_PIPELINE_ID"
    paths:
      - dist

pages:
  stage: deploy
  script:
    - mkdir public
    - mv dist/* public/
  artifacts:
    name: "$CI_PIPELINE_ID"
    paths:
      - public
    expire_in: 5 days
  when: always
  only:
    - develop

