import { toEuro, toFormattedDate, toMM, toMMYear, toMeters, toNAP, toScale, toSquareM, toYear } from "./formatters";


export const formattersByField = <Record<string, Function>> {
  restorationCosts: toEuro,
  velocity: toMMYear,
  surfaceArea: toSquareM,
  height: toMeters,
  groundWaterLevel: toNAP,
  groundLevel: toNAP,
  groundwaterLevelNet: toNAP,
  groundwaterLevelTemp: toNAP,
  pileHeadLevel: toNAP,
  pileTipLevel: toNAP,
  pileDiameterTop: toMM,
  pileDistanceLength: toMeters,
  pileDiameterBottom: toMM,
  concreteChargerLength: toMeters,
  woodPenetrationDepth: toMM,
  foundationDepth: toNAP,
  constructionLevel: toNAP,
  woodLevel: toNAP,
  masonLevel: toNAP,
  settlementSpeed: toMMYear,
  skewedParallel: toScale,
  thresholdFrontLevel: toNAP,
  skewedPerpendicular: toScale,
  thresholdBackLevel: toNAP,
  crackIndoorSize: toMM,
  crackFacadeFrontSize: toMM,
  crackFacadeBackSize: toMM,
  crackFacadeLeftSize: toMM,
  crackFacadeRightSize: toMM,
  drystand: toMeters,
  dewateringDepth: toMeters,
  createDate: toFormattedDate,
  documentDate: toFormattedDate,
  permitDate: toFormattedDate,
  recoveryDate: toFormattedDate,
  builtYear: toYear
}